export const AUDIT_SAMPLE_ROWS = [
  {
    id: "sample-1",
    Title: "5S Audit - Line A - Jan",
    Area: "Production",
    "Sub Area": "Line A",
    "5S": "Seiri",
    "5S Category": "Sorting",
    "5S Item": "Material tidak terpakai dipisah",
    "5S Validation": "OK",
    "Audit Photo": "",
    "Audit Score": 4,
    "Audit Remark": "Sudah rapi, tinggal label saja.",
    "Audit Status": "Open",
    "Follow Up Plan Date": "2026-02-05",
    "Follow Up Date": "",
    "Follow Up Photo": "",
    "Follow Up Score": "",
    "Follow Up Remark": "",
    "Follow Up Status": "Planned",
    "Reference Photo": "",
    Auditor: "Irwan",
    "Audit Date": "2026-01-29",
    Approvers: "Supervisor A",
    Auditee: "Operator 1",
    Responses: "",
    "Approval Creator": "Irwan",
    "Add Auditee": "",
    Auditee2: "",
    Modified: "2026-01-29T09:10:00Z",
    Created: "2026-01-29T09:00:00Z",
    "Created By": "Irwan",
    "Modified By": "Irwan",
  },
  {
    id: "sample-2",
    Title: "5S Audit - Warehouse - Jan",
    Area: "Warehouse",
    "Sub Area": "Rack 3",
    "5S": "Seiton",
    "5S Category": "Set in Order",
    "5S Item": "Penandaan lokasi pallet",
    "5S Validation": "NG",
    "Audit Photo": "",
    "Audit Score": 2,
    "Audit Remark": "Masih campur, perlu marking ulang.",
    "Audit Status": "In Progress",
    "Follow Up Plan Date": "2026-02-02",
    "Follow Up Date": "",
    "Follow Up Photo": "",
    "Follow Up Score": "",
    "Follow Up Remark": "",
    "Follow Up Status": "Planned",
    "Reference Photo": "",
    Auditor: "Irwan",
    "Audit Date": "2026-01-28",
    Approvers: "Manager W",
    Auditee: "Storeman 2",
    Responses: "",
    "Approval Creator": "Irwan",
    "Add Auditee": "",
    Auditee2: "",
    Modified: "2026-01-29T08:00:00Z",
    Created: "2026-01-28T15:20:00Z",
    "Created By": "Irwan",
    "Modified By": "Supervisor W",
  },
];

