export const AUDIT_FIELDS = [
  "Area",
  "Sub Area",
  "5S",
  "5S Category",
  "5S Item",
  "5S Validation",
  "Audit Photo",
  "Audit Score",
  "Audit Remark",
  "Audit Status",
  "Follow Up Plan Date",
  "Follow Up Date",
  "Follow Up Photo",
  "Follow Up Score",
  "Follow Up Remark",
  "Follow Up Status",
  "Reference Photo",
  "Auditor",
  "Audit Date",
  "Approvers",
  "Auditee",
  "Responses",
  "Approval Creator",
  "Title",
  "Add Auditee",
  "Auditee2",
  "Modified",
  "Created",
  "Created By",
  "Modified By",
];

